### ISSUE TITLE
Arrow Navigation

### ISSUE THREAD

**Issue by michalss** [jakky1/video_player_control_panel#5]
Can you please add arrow navigation to UI ? I think this is very important and it would make this package full..

Regards

**Comment by jakky1** [comment]
What does "arror navigation" mean ?

**Comment by jakky1** [comment]
I try to implement it.
Please let me know if it works for you.

Remember to modify your pubspec.yaml:
```yaml
dependencies:
  video_player_control_panel:
    git:
      url: https://github.com/jakky1/video_player_control_panel.git
      ref: master
```
